"""Shared helpers for the test-suite."""

from pathlib import Path

from firmware.config import Opts

CAMP_TMPL = """\
id: {cid}
name: test campaign
description: generated by tests
targets:
  - {target}
max_phases: 4
phases:
  - phase: recon
    plugin: recon-echo
"""


def write_campaign(tmpdir, cid, target, phases_yaml=""):
    path = Path(tmpdir) / ("%s.yaml" % cid)
    body = CAMP_TMPL.format(cid=cid, target=target)
    if phases_yaml:
        body = body.replace(
            "  - phase: recon\n    plugin: recon-echo\n", phases_yaml)
    path.write_text(body, encoding="utf-8")
    return path


def make_config(tmpdir, allowlist=("192.0.2.0/24",), live=False):
    opts = Opts(allowlist=[str(c) for c in allowlist])
    opts.output_dir = str(Path(tmpdir) / "reports")
    opts.audit_log = str(Path(tmpdir) / "logs" / "campaign.jsonl")
    opts.log_dir = str(Path(tmpdir) / "logs")
    opts.external_tools = {"live_execution": live}
    return opts


GATED_PHASES = """\
  - phase: recon
    plugin: recon-echo
  - phase: post
    plugin: post-echo
    requires_approval: true
"""